### ISSUE TITLE
Provide hook system

### ISSUE THREAD

**Issue by drupol** [reload/phing-drupal-template#10]
Hello,

I'm using your template in a company where websites are installed in subdirectories instead of vhost.
The problem is that the `.htaccess` needs to be modified accordingly and we need to update the `RewriteBase` directive.

I always try to keep your file (build.xml) original, and I've added to jenkins a `pre-build.xml` and a `post-build.xml`.
I've applied the changes in `post-build.xml` and everything is working fine but... **tests are failing**.

When you enable simpletests, it makes http request on the website (_through the --uri parameter, see [Issue 9](https://github.com/reload/phing-drupal-template/issues/9)_), and if the `.htaccess` is not correctly set, it produces a 404 and tests are failing.

I had to hack the [line 960](https://github.com/reload/phing-drupal-template/blob/master/build.xml#L960) and add a bit of code to update the `.htaccess`, I don't like that, but it's the only solution.

My idea would be to provide a "_hook system_" like for the '`make`' target. Of course, it could be extended to all targets.

How could we do ?

As far as I know Phing, one way to do that would be to provide an extra file with new targets like:
- **pre_make**: Target that would be executed before the make target.
- **post_make**: Target that would be executed after the make target.

What do you think ?

**Comment by pbuyle** [comment]
IMHO, you should patch build.xml around line 960 to add the required RewriteBase directive to .htaccess when a property with the value to use is set. So it won't change the behavior of the build for those who don't set the property. Then make a pull request for your changes.

**Comment by drupol** [comment]
Thanks, it's done, [see pull 13](https://github.com/reload/phing-drupal-template/pull/13)
