### ISSUE TITLE
Simpletests needs a valid website url to run tests properly.

### ISSUE THREAD

**Issue by drupol** [reload/phing-drupal-template#9]
If you do not provide a valid URI to drush, Simpletest will not run properly.

See d.o. comment: http://drupal.org/node/1243876#comment-5454076 and the link it refers to.

To solve this we could add a new property : project.uri and add the parameter in build.xml.

What do you think ?

**Comment by kasperg** [comment]
Sounds like a resonable solution.

**Comment by drupol** [comment]
Done, see [Pull 14](https://github.com/reload/phing-drupal-template/pull/14).
